version: '2'
services:
  spider:
    image: face-service:0.0.1
    network_mode: "bridge"
    ports:
      - "8100:8100"
    environment:
      - APP_PORT=8100
      - FACE_PATH=/opt/face/faces
    volumes:
      - ./faces:/opt/face/faces
      - ./web.py:/opt/face/web.py
    command: python ./web.py